##############################################################################
# Copyright 2022, 2024-2025 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: MacOS build

on:
  push:
  schedule:
    - cron: '0 0 15 * *'

jobs:
  build-macos-debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "MacOS 14", os: macos-14, osx_arch: "x86_64;arm64", build_type: "Debug" }
          - { name: "MacOS 14", os: macos-14, osx_arch: "x86_64;arm64", build_type: "Release" }
          - { name: "MacOS 15 Intel", os: macos-15-intel, osx_arch: "x86_64;arm64", build_type: "Debug" }
          - { name: "MacOS 15 Intel", os: macos-15-intel, osx_arch: "x86_64;arm64", build_type: "Release" }
          - { name: "MacOS 15", os: macos-15, osx_arch: "x86_64;arm64", build_type: "Debug" }
          - { name: "MacOS 15", os: macos-15, osx_arch: "x86_64;arm64", build_type: "Release" }

    name: ${{ matrix.name }} build (static/${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: git describe --always --dirty

    - name: Get version from git tag
      run: echo "GIT_DESCRIBE=$(git describe --always --dirty)" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B build -DCMAKE_OSX_ARCHITECTURES="${{ matrix.osx_arch }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}"

    - name: Build
      run: cmake --build build

    - name: Test
      run: cmake --build build --target test

    - name: Upload build directory if failed
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: libargp-${{ env.GIT_DESCRIBE }}-macos-build
        path: ./
        if-no-files-found: error
