##############################################################################
# Copyright 2022, 2024 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: MacOS build

on: [push]

jobs:
  build-macos-debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "MacOS 13", os: macos-13, osx_arch: "x86_64;arm64", build_type: "Debug" }
          - { name: "MacOS 13", os: macos-13, osx_arch: "x86_64;arm64", build_type: "Release" }
          - { name: "MacOS 14", os: macos-14, osx_arch: "x86_64;arm64", build_type: "Debug" }
          - { name: "MacOS 14", os: macos-14, osx_arch: "x86_64;arm64", build_type: "Release" }

    name: ${{ matrix.name }} build (static/${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: git describe --always --dirty

    - name: Configure CMake
      run: cmake -B build -DCMAKE_OSX_ARCHITECTURES="${{ matrix.osx_arch }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}"

    - name: Build
      run: cmake --build build

    - name: Test
      run: cmake --build build --target test
