##############################################################################
# Copyright 2022, 2024 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: Ubuntu build

on: [push]

jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Ubuntu 20.04", os: ubuntu-20.04, build_type: "Debug" }
          - { name: "Ubuntu 20.04", os: ubuntu-20.04, build_type: "Release" }
          - { name: "Ubuntu 22.04", os: ubuntu-22.04, build_type: "Debug" }
          - { name: "Ubuntu 22.04", os: ubuntu-22.04, build_type: "Release" }
          - { name: "Ubuntu 24.04", os: ubuntu-24.04, build_type: "Debug" }
          - { name: "Ubuntu 24.04", os: ubuntu-24.04, build_type: "Release" }

    name: ${{ matrix.name }} build (static/${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: git describe --always --dirty

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}"

    - name: Build
      run: cmake --build build

    - name: Test
      run: cmake --build build --target test
